//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Datum
{
    public int Id { get; set; }
    public string Name { get; set; }
    public int Int1 { get; set; }
    public int Int2 { get; set; }
    public int Int3 { get; set; }
    public int Int4 { get; set; }
    public int Int5 { get; set; }
    public int Int6 { get; set; }
    public int Int7 { get; set; }
    public int Int8 { get; set; }
    public int Int9 { get; set; }
    public string String1 { get; set; }
    public string String2 { get; set; }
    public string String3 { get; set; }
    public string String4 { get; set; }
    public string String5 { get; set; }
    public string String6 { get; set; }
    public string String7 { get; set; }
    public string String8 { get; set; }
    public string String9 { get; set; }
}

public partial class Question
{
    public int QuizId { get; set; }
    public string Quest { get; set; }
    public string Answers { get; set; }
    public string Ans { get; set; }
    public Nullable<int> Level { get; set; }
}

public partial class Score
{
    public string Name { get; set; }
    public int Marks { get; set; }
}
